### ISSUE TITLE
How do I adjust recoil sensitivity in LUA?

### ISSUE THREAD

**Issue by thman5588** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-27#2]
I'm a newb, but I am able to toggle the fire by hitting the wheel scroll button on my mouse (3) which activates everything, however how do I adjust the recoil amount? I play on higher DPS settings and the recoil is super intense at the following settings below, it literally scrolls down instantly. I have attached a copy of my settings 

General: 65
Vertical Multiplier: 1
Aim Sens: 60
ADS Sens: 60
Scoping Sens: 60

if you could help me out man, that would be awesome. This is a foreign language to me atm.

**Comment by Kava4** [comment]
You can change the "local mult=" value of your gun of choice. Increase it by 1 till your recoil is perfect.

**Comment by thman5588** [comment]
I tried increasing it by 1, however it makes the pull down more dramatic and i'm looking for the opposite effect. So if local mult=1 makes the pull downwards too extreme, should I change it to local mult= 0 or local mult= -1? I'm looking for the recoil to not drag downwards as much as the current setting.. I hope this helps clarify.

**Comment by Kava4** [comment]
Oh you want to lower the amount. Sorry this was just misunderstanding. Don't go below 0, it will give you inverted recoil. You can try 0.01, 0.1, 0.3 etc. (I believe that around 0.35 to 0.55 will be great for your sensitivity settings). Sadly I'm not on my pc and can't fix you right away.

**Comment by HaoHao993** [comment]
when it's active, when it's not , need guide , thanks :(

**Comment by othelloss** [comment]
Not working now, will there be an update? bro <3

**Comment by Bin0800** [comment]
> Oh you want to lower the amount. Sorry this was just misunderstanding. Don't go below 0, it will give you inverted recoil. You can try 0.01, 0.1, 0.3 etc. (I believe that around 0.35 to 0.55 will be great for your sensitivity settings). Sadly I'm not on my pc and can't fix you right away.

![image](https://github.com/Kava4/Pubg-Logitech-No-Recoil/assets/35598918/16171b17-e4da-4eac-b8e9-745e118a2acb)

I tried it but the script became unresponsive/active, I also used high dpi
