### ISSUE TITLE
can you use keyboard to active the script?

### ISSUE THREAD

**Issue by Pulse75** [Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-27#4]
example i want to use akm by pressing f2 key, can i do that?

**Comment by Kava4** [comment]
Only on Logitech keyboards.

**Comment by rizki0309** [comment]
I Have G512... G light Turn on how to assign G1 to your script

**Comment by rizki0309** [comment]
![keyboard setting](https://github.com/Kava4/PUBG-LOGITECH-NO-RECOIL-SEASON-28/assets/161566614/817a9592-e45c-416a-b720-fa2056a2094a)

hi, mouse (G502) key is working perfect, but i''m trying set on my G512 (LG HUB 2024.1) Keyboard with G Function ON (G light TURN ON), I try with key binding to 5 or F5 or G5 in your script its doesnt work...

what wrong with variable?
